name: Benchmark
on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:

env:
  PRISMA_TELEMETRY_INFORMATION: 'prisma benchmark.yml'

jobs:
  benchmark:
    name: all
    runs-on: ubuntu-latest
    # Only run on main repo (not on forks)
    # This avoids notifications to be sent to `alert-comment-cc-users`, see below
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: '16'

      - run: bash .github/workflows/scripts/setup.sh
        env:
          CI: true
          SKIP_GIT: true
          GITHUB_CONTEXT: ${{ toJson(github) }}

      #  This is required as setup.sh can modify pnpm-lock.yml
      - run: rm -f ./pnpm-lock.yaml

      - name: Run benchmarks
        run: pnpm run bench

      - name: Run benchmarks for Codspeed
        uses: CodSpeedHQ/action@v1
        with:
          run: pnpm run bench-stdout-only
          token: ${{ secrets.CODSPEED_TOKEN }}
